//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArcOrganization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArcOrganization.Resources.TextResources", typeof(TextResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string AccountTitle {
            get {
                return ResourceManager.GetString("AccountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string GeneralLoading {
            get {
                return ResourceManager.GetString("GeneralLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshing....
        /// </summary>
        public static string GeneralRefreshing {
            get {
                return ResourceManager.GetString("GeneralRefreshing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to see whats happening in your organization.
        /// </summary>
        public static string HubViewSubtitle {
            get {
                return ResourceManager.GetString("HubViewSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArcGIS Online for Organization.
        /// </summary>
        public static string HubViewTitle {
            get {
                return ResourceManager.GetString("HubViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most used.
        /// </summary>
        public static string MostUsedMapsTitle {
            get {
                return ResourceManager.GetString("MostUsedMapsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New services.
        /// </summary>
        public static string NewFeatureServicesTitle {
            get {
                return ResourceManager.GetString("NewFeatureServicesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New maps.
        /// </summary>
        public static string NewMapsTitle {
            get {
                return ResourceManager.GetString("NewMapsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search groups.
        /// </summary>
        public static string SearchGroupsTitle {
            get {
                return ResourceManager.GetString("SearchGroupsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search items.
        /// </summary>
        public static string SearchItemsTitle {
            get {
                return ResourceManager.GetString("SearchItemsTitle", resourceCulture);
            }
        }
    }
}
